config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  resources :tickets, except: [:edit] do
    member do
      post :conversations
    end
  end

  namespace :admin do
    resources :tickets, except: [:show] do
      member do
        match :conversations, via: [:get, :post]
      end
    end
  end
end

app/models/spree.rb
module Spree
  def self.table_name_prefix
    'spree_'
  end
end

app/models/spree/conversation.rb
module Spree
  class Conversation < Spree::Base
    belongs_to :ticket
    has_many_attached :files, dependent: :destroy

    belongs_to :sender, class_name: 'Spree::User', foreign_key: 'sender_id'
    belongs_to :reciever, class_name: 'Spree::User', foreign_key: 'reciever_id'

    def support?
      sender_name.downcase.match?('support')
    end

    def extract_initials_sender_name
      sender_name.split.map { |word| word[0] }.join.upcase
    end
  end
end

app/models/spree/ticket.rb
module Spree
  class Ticket < Spree::Base
    STATUS = %w(open in_progress closed awaiting).freeze
    PRIORITY = %w(high low medium).freeze
    CATEGORIES = ['Payments & Billing Issues',
                  'Login & Account Access',
                  'Order & Checkout Problems',
                  'Product & Service Inquiries',
                  'Shipping & Delivery Concerns',
                  'Returns & Exchanges',
                  'Technical Support',
                  'Feedback & Suggestions',
                  'Promotions & Discounts',
                  'Account Closure & Data Privacy'].freeze

    include Spree::Core::NumberGenerator.new(prefix: 'T')
    include NumberIdentifier
    include NumberAsParam
    include SingleStoreResource

    with_options presence: true do
      validates :email, length: { maximum: 254 }
      validates :store_id, :title, :customer_name
    end

    belongs_to :store
    belongs_to :assignee, class_name: 'Spree::User', foreign_key: 'assignee_id'
    belongs_to :user, class_name: 'Spree::User', foreign_key: 'user_id'
    
    has_many :conversations, dependent: :destroy
    has_many_attached :files, dependent: :destroy

    self.whitelisted_ransackable_associations = %w[conversations]
    self.whitelisted_ransackable_attributes = %w[number category order_no status priority customer_name email]

    scope :open_tickets, -> { where(status: 'open') }
    scope :running_tickets, -> { where(status: ['in_progress','awaiting']) }
    scope :solved_tickets, -> { where(status: 'closed') }
    def closed?
      status == 'closed'
    end

    def open?
      status == 'open'
    end

    def extract_initials_customer_name
      customer_name.split.map { |word| word[0] }.join.upcase
    end
  end
end

app/models/spree_support/spree/store_decorator.rb
module SpreeSupport
  module Spree
    module StoreDecorator
      def self.prepended(base)
        base.has_many :tickets
      end
    end
  end
end

::Spree::Store.prepend SpreeSupport::Spree::StoreDecorator

app/models/spree_support/spree/user_decorator.rb
module SpreeSupport
  module Spree
    module UserDecorator
      def self.prepended(base)
        base.has_many :tickets
      end
    end
  end
end

::Spree::User.prepend SpreeSupport::Spree::UserDecorator

app/controllers/spree/admin/tickets_controller.rb
module Spree
  module Admin
    class TicketsController < ResourceController

      before_action :find_resource, only: [:conversations]

      def conversations
        if request.post?
          @message = @ticket.conversations.build(conversation_params)

          @message.sender_name = 'Support'
          @message.sender = spree_current_user

          @message.reciever_name = @ticket.customer_name
          @message.reciever = @ticket.user

          @message.save
        end
      end

      private

      def collection
        return @collection if @collection.present?

        params[:q] ||= {}
        params[:q][:s] ||= 'created_at asc'

        @collection = ticket_scope

        @search = @collection.ransack(params[:q])
        @collection = @search.result.
                      page(params[:page]).
                      per(params[:per_page] || Spree::Backend::Config[:admin_products_per_page])

        @collection
      end

      def ticket_scope
        current_store.tickets.accessible_by(current_ability, :index)
      end

      def find_resource
        if parent_data.present?
          parent.send(controller_name).find_by(number: params[:id])
        else
          base_scope = model_class.try(:for_store, current_store) || model_class
          base_scope.find_by(number: params[:id])
        end
      end

      def conversation_params
        params.require(:conversation).permit(:message, files: [])
      end
    end
  end
end

app/controllers/spree/tickets_controller.rb
module Spree
  class TicketsController < Spree::StoreController

    before_action :set_ticket, only: %i[ show conversations ]

    load_and_authorize_resource class: Spree::Ticket

    def index
      @tickets = Spree::Ticket.all
    end

    def new
      @ticket = Spree::Ticket.new
    end

    def show
    end

    def create
      @ticket = current_store.tickets.new(ticket_params)

      respond_to do |format|
        if @ticket.save
          format.html { redirect_to tickets_url, notice: "ticket was successfully created." }
          format.json { render :show, status: :created, location: @ticket }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @ticket.errors, status: :unprocessable_entity }
        end
      end
    end

    def conversations
      @message = @ticket.conversations.build(conversation_params)

      @message.sender_name = @ticket.customer_name
      @message.sender = spree_current_user

      @message.reciever_name ||= 'Support'
      @message.reciever = @ticket.assignee

      if @message.save
        respond_to do |format|
          format.html { redirect_to @ticket, notice: 'Message was successfully created.' }
          format.turbo_stream
        end
      else
        flash[:error] = @message.errors.full_messages.join(', ')
        redirect_to conversations_ticket_path(@ticket)
      end
    end

    private

    def set_ticket
      @ticket = Spree::Ticket.find_by(number: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:customer_name, :email, :phone_number, :title, :category, :order_no, :description, :user_id, files: [])
    end

    def conversation_params
      params.require(:conversation).permit(:message, files: [])
    end
  end
end

app/helpers/spree/admin/tickets_helper.rb
module Spree
  module Admin
    module TicketsHelper

      def priority_tag(ticket)
        case ticket.priority
        when 'low'
          build_priority_tag('low', 'danger')
        when 'medium'
          build_priority_tag('medium', 'warning')
        when 'high'
          build_priority_tag('high', 'success')
        else
          build__default_priority_tag
        end
      end

      def status_tag(ticket)
        case ticket.status
        when 'open'
          build_status_tag('Open', 'success')
        when 'in_progress'
          build_status_tag('In Progress', 'warning')
        when 'closed'
          build_status_tag('Closed', 'danger')
        when 'awaiting'
          build_status_tag('Awaiting Response', 'info')
        end
      end

      private

      def build_priority_tag(priority, text_class)
        content_tag(:img, nil, alt: "#{priority} priority".titleize, width: '12px', height: '12px', src: image_path("backend-custom-#{priority}-priority.svg")
          ) << content_tag(:p, priority.titleize, class: "text-#{text_class} mb-0 ml-2") 
      end

      def build__default_priority_tag
        content_tag(:p, 'Not Define', class: 'text-info mb-0 ml-2') 
      end

      def build_status_tag(status, bg_class)
        content_tag(:span, status.titleize, class: "bg-#{bg_class} mb-0 ml-2 bg-success rounded-pill py-1 px-2 text-12") 
      end
    end
  end
end

app/helpers/spree/tickets_helper.rb
module Spree
  module TicketsHelper

    def class_text_colour(ticket)
      case ticket.status
      when 'open'
        'text-danger'
      when 'in_progress'
        'text-info'
      when 'closed'
        'text-success'
      when 'awaiting'
        'text-primary'
      else
        'text-secondary'
      end
    end

    def add_border_inbetween(idx)
      @tickets.count != (idx + 1) ? 'border-bottom border-lightgray' : ''
     end
  end
end

app/views/spree/admin/shared/_content_header.html.erb
<div id="contentHeader" class="row mb-0 pb-0 mt-4">
  <% if content_for?(:page_title) || content_for?(:page_actions) %>
    <div class="content-header col <%= "with-page-tabs" if content_for?(:page_tabs) %> page-header">
      <div id="contentHeaderRow" class="row align-items-center  <%= if content_for?(:page_tabs) then "pb-3" else "pb-3 mb-3" end %>">

        <% if content_for?(:page_title) %>
          <h2 class="px-2 px-md-0 mb-0 col d-flex align-items-center">
            <%= yield :page_title %>
            <% if content_for?(:page_title_small) %>
              <small><%= yield :page_title_small %></small>
            <% end %>
          </h2>
        <% end %>

        <% if content_for?(:page_actions) %>
          <div class="page-actions pl-0 pr-0 d-none d-lg-flex" data-hook="toolbar">
            <%= yield :page_actions %>
          </div>
        <% end %>

        <% if content_for?(:page_actions) %>
          <div class="d-flex d-lg-none justify-content-end m-0 p-0">
            <button type="button"
                    id="contextual-menu-toggle"
                    class="btn btn-light">
                    <span class="d-none d-sm-inline">
                      <%= Spree.t('more') %>
                    </span>
                    <%= svg_icon name: "chevron-down.svg", width: '16', height: '16' %>
            </button>
          </div>
        <% end %>
      </div>

      <% if content_for?(:page_tabs) %>
        <div class="row my-2 mb-3 pb-1 pt-1 align-items-center" data-nav-x-wrapper>
          <div data-nav-x-container class="w-100">
            <ul id="spreePageTabs" class="nav nav-pills flex-nowrap" data-nav-x-content>
              <%= yield :page_tabs %>
            </ul>
          </div>

          <button class="nav-x_Advancer nav-x_Advancer_Left" type="button">
            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z" />
            </svg>
          </button>

          <button class="nav-x_Advancer nav-x_Advancer_Right" type="button">
            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z" />
            </svg>
          </button>
        </div>
      <% end %>

    </div>
  <% end %>
</div>

app/views/spree/admin/tickets/_chat.html.erb
<%= turbo_frame_tag 'admin_dashboard_ticket_conversations' do %>
  <% if @ticket.conversations.any? %>
    <% @ticket.conversations.each do |conversation| %>
      <div class="row row-cols-2 align-items-center">
        <div class="col-2">
          <strong class="text-capitalize"> <%= conversation.sender_name %></strong>
          <p class="mb-0"><%= conversation.created_at.strftime('%A %d %B %Y') %></p>
        </div>
        <div class="col-10 text-break"><%= conversation.message %></div>
      </div>


      <div class="row row-cols-2 align-items-center">
        <div class="col-2">
          <%#  %>
        </div>
        <div class="col-10 d-flex flex-wrap gap-20">
        <!-- Display other message details as needed -->
         <% conversation.files.each_with_index do |file, idx| %>
         <div class="d-flex border align-items-center py-2 px-3 rounded-lg mt-2 uploaded-file">
            <%= image_tag('backend-custom-file-icon.svg', alt: 'Send', width: '40px', height: '40px') %>
            <p class="mb-0">
              <% file_url = Rails.application.routes.url_helpers.url_for(file) %>
              <%= link_to file.blob.filename.to_s, file_url, target: "_blank" %>
            </p>
          </div>
          <% end %>
        </div>
      </div>

      <hr>
    <% end %>
  <% else %>
    <div class="text-center no-objects-found m-5">
      <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Conversation)) %>!
    </div>
  <% end %>
<% end %>

app/views/spree/admin/tickets/_chat_form.html.erb
<%= turbo_frame_tag 'admin_dashboard_ticket_conversations_chat_form' do %>
  <%= form_for [:admin, @ticket.conversations.new], url: conversations_admin_ticket_path(@ticket), data: { controller: "turbo-stream" } do |f| %>
    <fieldset class="row row-cols-2 align-items-center">
      <div class="col-2">
        <strong class="text-capitalize"><%= @ticket.assignee.email rescue 'Support' %></strong>
        <p class="mb-0"><%= DateTime.now.strftime('%A %d %B %Y') %></p>
      </div>
      <div class="d-flex drop-message border rounded-lg px-0 col-10">
        <div>
          <%= f.file_field :files, multiple: true, placeholder: 'Upload Files', class: 'mt-4 d-none', id: 'upload-file', onchange: 'handleFileUpload(this)' %>
          <label for="upload-file" class="h-100 mb-0">
            <p class="chat-upload-button h-100 d-flex align-items-center px-3">
              <%= image_tag('frontend-custom-attach-file.svg', alt: 'Add attachment', width: '15px', height: '20px') %>
            </p>
          </label>
        </div>
        <div class="w-100">
          <%= f.field_container :message do %>
            <%= f.text_field :message, {class: "w-100 form-control border-0 mb-0 shadow-none", placeholder: "Type your message here"} %>
            <%= f.error_message_on :message %>
            <div class="d-flex" id="file-info"></div>
          <% end %>
        </div>
        <%= button_tag class: 'chat-send-button text-white h-100 d-flex align-items-center px-2', id: 'add-to-cart-button', type: :submit do %>
          <%= image_tag('backend-custom-send-white.svg', alt: 'Send', width: '18px', height: '15px') %>
        <% end %>
      </div>
    </fieldset>
  <% end %>
<% end %>

<script>
function handleFileUpload(input) {
  const fileInfoContainer = $('#file-info').empty();
  const numFiles = input.files.length;

  fileInfoContainer.append(`<div mr-3><%= image_tag('backend-custom-file-icon.svg', alt: 'pdf', width: '40px', height: '40px') %></div>`);

  fileInfoContainer.append(`<p class="mb-0">${numFiles} file${numFiles !== 1 ? 's' : ''} uploaded</p>`);
}
</script>

app/views/spree/admin/tickets/_filters.html.erb
<div data-hook="admin_products_sidebar">
  <%= search_form_for [:admin, @search] do |f| %>
    <div data-hook="admin_products_index_search" class="row">
      <div class="col-12 col-lg-6">
        <div class="form-group">
          <%= f.label :order_no_eq, 'Order Number' %>
          <%= f.text_field :order_no_eq, size: 15, class: "form-control js-quick-search-target js-filterable" %>
        </div>
      </div>
      <div class="col-12 col-lg-6">
        <div class="form-group">
          <%= f.label :number_eq, 'Ticket No.' %>
          <%= f.text_field :number_eq, size: 15, class: "form-control js-filterable" %>
        </div>
      </div>
      <div class="col-12 col-lg-6">
        <div class="form-group">
          <%= f.label :customer_name, 'Customer Name' %>
          <%= f.text_field :customer_name, size: 15, class: "form-control js-filterable" %>
        </div>
      </div>

      <div class="col-12 col-lg-6">
        <div class="form-group">
          <%= f.label :email_cont, 'Email' %>
          <%= f.text_field :email_cont, size: 15, class: "form-control js-filterable" %>
        </div>
      </div>
      <div class="col-12 col-lg-6">
        <div class="form-group">
          <%= f.label :status_eq, 'Status' %>
          <%= f.text_field :status_eq, size: 15, class: "form-control js-filterable" %>
        </div>
      </div>
    </div>
    <div data-hook="admin_products_index_search_buttons" class="form-actions">
      <%= button Spree.t(:filter_results), 'search.svg' %>
    </div>
  <% end %>
</div>

app/views/spree/admin/tickets/_form.html.erb
<div class="row new-ticket rounded-lg">
  <div data-hook="new_product_sku" class="col-12 col-md-4">
    <%= f.field_container :title do %>
      <%= f.label :title, raw(Spree.t(:title) + required_span_tag) %>
      <%= f.text_field :title, class: 'form-control', placeholder: 'Enter Here' %>
      <%= f.error_message_on :title %>
    <% end %>
  </div>

  <div data-hook="new_product_sku" class="col-12 col-md-4">
    <%= f.field_container :order_no do %>
      <%= f.label :order_no, raw(Spree.t(:order_no) + required_span_tag) %>
      <%= f.text_field :order_no, class: 'form-control', placeholder: 'Enter Here' %>
      <%= f.error_message_on :order_no %>
    <% end %>
  </div>
 
  <div class="col-12 col-md-4">
    <%= f.field_container :priority do %>
      <%= f.label :priority, raw(Spree.t(:priority) + required_span_tag) %>
      <%= f.select :priority, Spree::Ticket::PRIORITY.map { |priority | [ priority.titleize, priority ] }, { prompt: Spree.t(:select_priority) }, { class: 'form-control select2' } %>
      <%= f.error_message_on :priority %>
    <% end %>
  </div>

  <div data-hook="new_product_sku" class="col-12 col-md-4">
    <%= f.field_container :customer_name do %>
      <%= f.label :customer_name, raw(Spree.t(:customer_name) + required_span_tag) %>
      <%= f.text_field :customer_name, class: 'form-control' %>
      <%= f.error_message_on :customer_name %>
    <% end %>
  </div>
 
   <div data-hook="new_product_sku" class="col-12 col-md-4">
    <%= f.field_container :email do %>
      <%= f.label :email, raw(Spree.t(:email) + required_span_tag) %>
      <%= f.email_field :email, class: 'form-control' %>
      <%= f.error_message_on :email %>
    <% end %>
  </div>

  <div class="col-12 col-md-4">
    <%= f.field_container :assignee_id do %>
      <%= f.label :assignee_id, raw(Spree.t(:assignee) + required_span_tag) %>
      <%= f.select :assignee_id, Spree::User.pluck(:email, :id), { include_blank: true }, { class: 'form-control select2' } %>
      <%= f.error_message_on :assignee_id %>
    <% end %>
  </div>

  <div data-hook="new_product_sku" class="col-12 col-md-4">
    <%= f.field_container :category do %>
      <%= f.label :category, raw(Spree.t(:category) + required_span_tag) %>
      <%= f.text_field :category, class: 'form-control' %>
      <%= f.error_message_on :category %>
    <% end %>
  </div>
 
  <div class="col-12 col-md-4">
    <%= f.field_container :status do %>
      <%= f.label :status, raw(Spree.t(:status) + required_span_tag) %>
      <%= f.select :status, Spree::Ticket::STATUS.map { |state| [ state.titleize, state ] }, {}, { class: 'form-control select2' } %>
      <%= f.error_message_on :status %>
    <% end %>
  </div>

  <div data-hook="new_product_sku" class="col-12 col-md-4">
    <%= f.field_container :phone_number do %>
      <%= f.label :phone_number, raw(Spree.t(:phone_number) + required_span_tag) %>
      <%= f.phone_field :phone_number, class: 'form-control' %>
      <%= f.error_message_on :phone_number %>
    <% end %>
  </div>

  <div class="col-12 col-md-8">
    <%= f.field_container :description do %>
      <%= f.label :description, raw(Spree.t(:description) + required_span_tag) %>
      <%= f.text_area :description, { rows: "5", class: "form-control" } %>
      <%= f.error_message_on :description %>
    <% end %>
  </div>

    <div class="col-12 d-flex flex-wrap gap-20">
      <%- if @ticket.files.present? %>
        <% @ticket.files.each_with_index do |file, idx| %>
        <div class="d-flex border align-items-center py-2 px-3 rounded-lg mt-2 uploaded-file">
          <%= image_tag('backend-custom-file-icon.svg', alt: 'Send', width: '40px', height: '40px') %>
          <p class="mb-0">
            <% url = Rails.application.routes.url_helpers.url_for(file) %>
            <%= link_to file.blob.filename.to_s, url, target: "_blank" %>
          </p>
        </div>
        <% end %>
      <% end %>
    </div>

  <div class="col-12">
    <%= f.field_container :files do %>
      <%= f.label :files, raw(Spree.t(:files) + required_span_tag), class: 'd-flex' %>
        <%= f.file_field :files, multiple: true, id: 'attach-file', class: 'd-none' %>
        <label for='attach-file'>
          <div class='d-flex align-items-center bg-transparent add-attachment'>
            <%= image_tag('frontend-custom-upload.svg', alt: 'Add attachment', width: '16px', height: '16px') %>
            <p class="mb-0 ml-3">Add Attachment</p>
          </div>
        </label>
        <div class="d-flex file-uploaded" id="file-info"></div>
      <%= f.error_message_on :files %>
    <% end %>
  </div>
</div>

app/views/spree/admin/tickets/conversations.turbo_stream.erb
<%= turbo_stream.update "admin_dashboard_ticket_conversations" do %>
  <%= render partial: 'spree/admin/tickets/chat' %>
<% end %>

<%= turbo_stream.update "admin_dashboard_ticket_conversations_chat_form" do %>
  <%= render partial: 'spree/admin/tickets/chat_form' %>
<% end %>

app/views/spree/admin/tickets/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::Ticket) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_ticket), new_object_url, { class: "btn-success", icon: 'add.svg', id: 'admin_new_ticket' } %>
<% end if can?(:create, Spree::Ticket) %>

<% content_for :page_tabs do %>
  <li class="nav-item">
    <%= link_to Spree.t('admin.ticket.all'),
                spree.admin_tickets_path,
                class: "nav-link #{'active' if params[:q][:status_eq].blank?}" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Open',
                params.merge({q: {status_eq: 'open'}}).permit!,
                class: "nav-link #{'active' if params[:q][:status_eq] == 'open'}" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Awaiting Response',
                params.merge({q: {status_eq: 'awaiting'}}).permit!,
                class: "nav-link #{'active' if params[:q][:status_eq] == 'awaiting'}" %>
  </li>
  <li class="nav-item">
    <%= link_to 'In progress',
                params.merge({q: {status_eq: 'in_progress'}}).permit!,
                class: "nav-link #{'active' if params[:q][:status_eq] == 'in_progress'}" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Closed',
                params.merge({q: {status_eq: 'closed'}}).permit!,
                class: "nav-link #{'active' if params[:q][:status_eq] == 'closed'}" %>
  </li>
<% end  %>

<% content_for :table_filter do %>
  <%= render partial: 'filters' %>
<% end %>

<% if @collection.any? %>
<div class="table-responsive border rounded bg-white">
  <table class="table">
    <thead class="text-muted">
      <tr>
        <th scope="col" class="text-center"><%= 'Ticket No.' %></th>
        <th scope="col" class="text-center"><%= sort_link @search, :customer_name, Spree.t(:customer_name), { default_order: "desc" }, {} %></th>
        <th scope="col" class="text-center"><%= 'Order No.' %></th>
        <th scope="col" class="text-center"><%= 'Priority' %></th>
        <th scope="col" class="text-center"><%= 'Created No' %></th>
        <th scope="col" class="text-center"><%= 'Status' %></th>
        <th scope="col" class="text-center"><%= 'Email' %></th>
        <th scope="col" class="text-center"><%= 'Phone No.' %></th>
        <th scope="col" class="text-center"><%= 'Asignee' %></th>
        <th scope="col" class="text-center" class="actions"><%= 'Actions' %></th>
      </tr>
    </thead>
    <tbody>
      <% @collection.each do |ticket| %>
        <tr class="<%= cycle('odd', 'even') %>">
          <td class="text-center"><%= link_to ticket.number, edit_admin_ticket_path(ticket) %></td>
          <td class="text-center"><%= ticket.customer_name %></td>
          <td class="text-center"><%= ticket.order_no rescue '--' %></td>
          <td class="text-center">
            <div class="d-flex align-items-center justify-content-center">
              <%= priority_tag(ticket) %>
            </div>
          </td>
          <td class="text-center"><%= ticket.created_at %></td>
          <td class="text-center">
            <%= status_tag(ticket) %>
          </td>
          <td class="text-center"><%= ticket.email %></td>
          <td class="text-center"><%= ticket.phone_number %></td>
          <td class="text-center"><%= ticket.try(:assignee).try(:email) %></td>
          <td class="actions ">
            <span class="d-flex justify-content-center">
              <%= link_to_edit ticket, no_text: true, class: 'edit' if can?(:edit, ticket) %>
            </span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% else %>
  <div class="text-center no-objects-found m-5">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Ticket)) %>,
    <%= link_to Spree.t(:add_one), new_object_url if can?(:create, Spree::Ticket) %>!
  </div>
<% end %>

<%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @collection } %>

app/views/spree/admin/tickets/new.html.erb
<% content_for :page_title do %>
  <%= page_header_back_button spree.admin_tickets_path %>
  <%= Spree.t(:new_ticket) %>
<% end %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @ticket } %>

<%= form_for [:admin, @ticket] do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <div class="mt-4">
      <%= render partial: 'spree/admin/shared/new_resource_links' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/tickets/index.html.erb
<div class="container tickets mb-5">
  <div class="d-sm-flex justify-content-between align-items-center">
    <h1 class="mb-0">Recent Raised Tickets</h1>
    <%= link_to 'Raise Ticket', new_ticket_path, class: 'btn btn-primary my-3' %>
  </div>

  <div class="ticket-listing pt-0">
    <% @tickets.each_with_index.each do |ticket, idx| %>
        <div class="d-sm-flex justify-content-between align-items-center mt-5 pb-4 <%= add_border_inbetween(idx) %>">
          <div>
            <p class="ticket-description"><%= ticket.description %></p>
            <div class="d-flex ticket-detail mt-2 align-items-center">
              <p class="<%= class_text_colour(ticket) %>"><%= Spree.t(ticket.status, scope: 'frontend.support.status')  %></p>
              <p><%= ticket.category %></p>
              <p class="border-right-0"><%= ticket.created_at.strftime("%a, %d %b") %></p>
            </div>
          </div>
          <p class="mt-2 mt-sm-0"><ins><%= link_to 'View', ticket_path(ticket) %></ins></p>
        </div>
    <% end %>
  </div>
</div>

app/views/spree/tickets/new.html.erb
<%= render 'spree/shared/error_messages', target: @ticket %>
<div class="col-lg-6 offset-lg-3">
  <h1 class="spree-header spree-mb-large spree-mt-large"><%= 'Create Ticket' %></h1>
  <%= form_for @ticket, html: { id: 'checkout_form_address' },  multipart: true do |f| %>
    <%= render 'form', f: f %>

    <%= f.submit 'Create', class: 'btn btn-primary btn-block spree-btn mb-5' %>

    <%= link_to 'Cancel', tickets_path , class: 'btn-outline-dark btn btn-block spree-btn mb-5 text-20' %>
  <% end %>
</div>